- name: Installing packages through loops
  hosts: localhost
  become: yes
  tasks:
  - name: Installing 
    ansible.builtin.debug:
      name: "{{item}}"
      state: prasent
    loop:
    - git
    - wget
    - mysql
    - postfix

