- name: Packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing or uninstalling Packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'absent'}
    - {name: 'mysql', state: 'present'}
    - {name: 'wget', state: 'absent'}
    - {name: 'postfix', state: 'absent'}